# Generated by Django 5.1.3 on 2024-12-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['email'], 'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
