# Generated by Django 5.1.3 on 2024-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_month',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha final de prueba'),
        ),
    ]
