# Generated by Django 5.1.3 on 2024-12-11 08:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_trial_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_subscription',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha suscripción'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_month',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha final suscripción'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trial_month',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha final de prueba'),
        ),
    ]
