# Generated by Django 5.1.3 on 2024-12-13 06:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_date_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_subscription',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha suscripción'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_month',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha final suscripción'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trial_month',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha final de prueba'),
        ),
    ]
