# Generated by Django 5.1.3 on 2024-11-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField(verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.contry', verbose_name='Pais')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='Equipo')),
                ('image', models.ImageField(upload_to='team', verbose_name='Imagen')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('gol_home_ht', models.IntegerField(verbose_name='Goles Equipo Local HT')),
                ('gol_visit_ht', models.IntegerField(verbose_name='Goles Equipo Visitante HT')),
                ('gol_home_ft', models.IntegerField(verbose_name='Goles Equipo Local FT')),
                ('gol_visit_ft', models.IntegerField(verbose_name='Goles Equipo Visitante FT')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.league', verbose_name='Liga')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='forecasts.team', verbose_name='Equipo local')),
                ('visit_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_matches', to='forecasts.team', verbose_name='Equipo visitante')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['league'],
            },
        ),
    ]
