# Generated by Django 5.1.3 on 2024-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='soccer_day',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Jornada'),
        ),
    ]
