# Generated by Django 5.1.3 on 2024-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_match_soccer_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gol_home_ft',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles Equipo Local FT'),
        ),
        migrations.AlterField(
            model_name='match',
            name='gol_home_ht',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles Equipo Local HT'),
        ),
        migrations.AlterField(
            model_name='match',
            name='gol_visit_ft',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles Equipo Visitante FT'),
        ),
        migrations.AlterField(
            model_name='match',
            name='gol_visit_ht',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles Equipo Visitante HT'),
        ),
    ]
