# Generated by Django 5.1.3 on 2024-11-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_alter_match_gol_home_ft_alter_match_gol_home_ht_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='contry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contry', verbose_name='Imagen'),
        ),
    ]
