# Generated by Django 5.1.3 on 2024-12-03 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_league_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('over_05_ht', models.PositiveSmallIntegerField()),
                ('valor_ini_over_05_ht', models.PositiveSmallIntegerField()),
                ('valor_fin_over_05_ht', models.PositiveSmallIntegerField()),
                ('over_15_ht', models.PositiveSmallIntegerField()),
                ('valor_ini_over_15_ht', models.PositiveSmallIntegerField()),
                ('valor_fin_over_15_ht', models.PositiveSmallIntegerField()),
                ('over_05_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_over_05_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_over_05_ft', models.PositiveSmallIntegerField()),
                ('over_15_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_over_15_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_over_15_ft', models.PositiveSmallIntegerField()),
                ('over_25_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_over_25_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_over_25_ft', models.PositiveSmallIntegerField()),
                ('aem', models.PositiveSmallIntegerField()),
                ('valor_ini_aem', models.PositiveSmallIntegerField()),
                ('valor_fin_aem', models.PositiveSmallIntegerField()),
                ('local_anota_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_local_anota_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_local_anota_ft', models.PositiveSmallIntegerField()),
                ('local_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_ini_local_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_fin_local_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('local_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_ini_local_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_fin_local_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('visitante_anota_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_anota_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_anota_ft', models.PositiveSmallIntegerField()),
                ('visitante_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_anota_mitad_1', models.PositiveSmallIntegerField()),
                ('visitante_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_anota_mitad_2', models.PositiveSmallIntegerField()),
                ('local_concede_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_local_concede_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_local_concede_ft', models.PositiveSmallIntegerField()),
                ('local_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_ini_local_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_fin_local_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('local_concede_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_ini_local_concede_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_fin_local_concede_mitad_2', models.PositiveSmallIntegerField()),
                ('visitante_concede_ft', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_concede_ft', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_concede_ft', models.PositiveSmallIntegerField()),
                ('visitante_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_concede_mitad_1', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_concede_mitad_2', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_concede_mitad_2', models.PositiveSmallIntegerField()),
                ('local_favorito', models.PositiveSmallIntegerField()),
                ('valor_ini_local_favorito', models.PositiveSmallIntegerField()),
                ('valor_fin_local_favorito', models.PositiveSmallIntegerField()),
                ('visitante_favorito', models.PositiveSmallIntegerField()),
                ('valor_ini_visitante_favorito', models.PositiveSmallIntegerField()),
                ('valor_fin_visitante_favorito', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
            },
        ),
    ]
