# Generated by Django 5.1.3 on 2024-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='aem',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_anota_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_anota_mitad_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_anota_mitad_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_concede_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_concede_mitad_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_concede_mitad_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='local_favorito',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='over_05_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='over_05_ht',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='over_15_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='over_15_ht',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='over_25_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_aem',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_anota_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_anota_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_anota_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_concede_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_concede_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_concede_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_local_favorito',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_over_05_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_over_05_ht',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_over_15_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_over_15_ht',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_over_25_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_anota_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_anota_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_anota_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_concede_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_concede_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_concede_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_fin_visitante_favorito',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_aem',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_anota_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_anota_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_anota_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_concede_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_concede_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_concede_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_local_favorito',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_over_05_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_over_05_ht',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_over_15_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_over_15_ht',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_over_25_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_anota_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_anota_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_anota_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_concede_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_concede_mitad_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_concede_mitad_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='valor_ini_visitante_favorito',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_anota_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_anota_mitad_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_anota_mitad_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_concede_ft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_concede_mitad_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='visitante_favorito',
            field=models.BooleanField(),
        ),
    ]
