# Generated by Django 5.1.3 on 2024-12-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_alter_strategy_aem_alter_strategy_local_anota_ft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='aem',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_anota_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_anota_mitad_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_anota_mitad_2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_concede_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_concede_mitad_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_concede_mitad_2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='local_favorito',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='over_05_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='over_05_ht',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='over_15_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='over_15_ht',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='over_25_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_anota_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_anota_mitad_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_anota_mitad_2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_concede_ft',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_concede_mitad_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='visitante_favorito',
        ),
    ]
