# Generated by Django 5.1.3 on 2024-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0008_remove_strategy_aem_remove_strategy_local_anota_ft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goles_tramo_11_20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 11 al 20'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_1_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 1 al 10'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_21_30',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 21 al 30'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_31_40',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 31 al 40'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_41_50',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 41 al 50'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_51_60',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 51 al 60'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_61_70',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 61 al 70'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_71_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 71 al 80'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_81_90',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 81 al 90'),
        ),
        migrations.AddField(
            model_name='match',
            name='goles_tramo_91_final',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles del 91 al final'),
        ),
    ]
